Apply auth also for private pypi packages
conda/conda-lock pull request #323
Opened 2023-01-29 20:18 UTC by croth1

previous logic converted all lock files to explicit type and ignored all lines starting with `#`or `@`.  This however does not allow adding auth to packages from private pypi indices, as they are represented as `# pip package @ index_url` and thus were skipped in the auth re-adding logic.

2023-02-07 16:19 UTC, croth1 commented
@maresb whom do I need to bribe to get this reviewed? :)

2023-02-08 01:11 UTC, maresb commented
Hi @croth1! I don't have much time these days, but at least this one is nice and short!

You could start by bribing me with a test case so that we can prevent regressions. :slightly_smiling_face: Thanks!

2023-02-14 16:00 UTC, croth1 commented
@maresb, I integrated the new logic into existing test cases - strictly speaking the auth stripping logic does not seem to be needed for pypi, as the current poetry code does that automatically.
However this way the pypi auth logic is the same as the conda auth logic and was a bit easier to integrate into the tests. Hope that's fine with you.

2023-02-14 18:30 UTC, maresb requested changes
Thanks so much @croth1 for your persistence and patience on this!!!

(I wasn't so familiar with this code, so even though this is straightforward, it's been tricky for me to find the time to look properly at this. Not to mention that the current directory structure for these test files confuses me; perhaps we should eventually clean that up.)

This looks really excellent. Could you please add test cases for `test__add_auth_to_line`, `test__strip_auth_from_line`, `test__extract_domain`? Luckily these tests are self-contained, so I think this will be quick and easy.

Once that's done, it looks good from my side. Anything to add, @mariusvniekerk?

2023-02-14 18:30 UTC, maresb commented on conda_lock/conda_lock.py
>  # Captures basic auth credentials, if they exists, in the second capture group.
```suggestion
# Captures basic auth credentials, if they exists, in the third capture group.
```

2023-02-14 18:30 UTC, maresb commented on conda_lock/conda_lock.py
>  # Captures the domain in the second group.
```suggestion
# Captures the domain in the third group.
```

2023-02-16 19:45 UTC, maresb approved these changes

2023-02-16 21:36 UTC, maresb commented
Thanks so much @croth1!!!

2023-02-16 21:38 UTC, merged